capstone_depot/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, FieldList, FormField
from flask_wtf.file import FileField, FileAllowed
from wtforms.validators import DataRequired

YEARS = sorted([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025], reverse=True)

# Build select choices with a disabled placeholder on top
LATEST_YEAR = YEARS[0]
# Use integer coercion so prepopulation with model ints works seamlessly.
# Placeholder uses 0 which will fail DataRequired (false-y) until a real year is chosen.
YEAR_CHOICES = [(0, f"Select year ({LATEST_YEAR})")] + [(y, y) for y in YEARS]

DEPARTMENTS_BASE = [
    'Chemical Engineering', 'Civil Engineering', 'Computer Engineering', 'Software Engineering',
    'Electrical Engineering', 'Engineering Physics', 'Materials Engineering', 'Mechanical Engineering',
    'Mining Engineering', 'Petroleum Engineering', 'Biomedical Engineering (MSc)'
]
DEPARTMENTS_SORTED = sorted(DEPARTMENTS_BASE)
TOP_DEPARTMENT = DEPARTMENTS_SORTED[0]
CATEGORY_CHOICES = [("", f"Choose department ({TOP_DEPARTMENT})")] + [(c, c) for c in DEPARTMENTS_SORTED]

# Backwards-compatible export for routes expecting CATEGORIES
CATEGORIES = [" "] + DEPARTMENTS_SORTED

class TeamMemberField(FlaskForm):
    name = StringField('Team Member')
    linkedin_url = StringField('LinkedIn URL')

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    year = SelectField('Select the year you completed your project', choices=YEAR_CHOICES, coerce=int, validate_choice=True, validators=[DataRequired()])
    team_members = StringField('Add team members', validators=[DataRequired()])
    category = SelectField('Choose your department', choices=CATEGORY_CHOICES, validate_choice=True, validators=[DataRequired()])
    content = TextAreaField('Give a description of the project', validators=[DataRequired()])
    link = StringField('Enter link to presentation (Optional)')
    poster = FileField('Upload Presentation Poster (Accepted filetypes: jpg, png)', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Upload')

capstone_depot/categories/routes.py
from flask import render_template, request, Blueprint
from capstone_depot.models import Post
from capstone_depot.posts.forms import CATEGORIES

categories = Blueprint('categories', __name__)

@categories.route("/category/<string:category>")
def category_posts(category):
    """
    Display posts from a specific category.

    Args:
        category: The category (Computer Engineering, Electrical Engineering)... to filter the posts against.
    """
    page = request.args.get('page', 1, type=int)
    category_posts = Post.query.filter_by(category=category).order_by(Post.year.desc()).paginate(page=page, per_page=10)
    return render_template('home.html',category=category, posts=category_posts, categories=CATEGORIES[1:])

capstone_depot/main/routes.py
from flask import render_template, request, Blueprint
from capstone_depot.models import Post
from capstone_depot.posts.forms import CATEGORIES

main = Blueprint('main', __name__)

@main.route("/") # handles all the server actions and provides endpoint
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.year.desc(), Post.id.desc()).paginate(page=page, per_page=10)
    return render_template('home.html', posts=posts, categories=CATEGORIES[1:])


@main.route("/about")
def about():
    return render_template('about.html', title='About')

capstone_depot/posts/routes.py
"""
This file contains all the routes that are related to posts on Capstone Depot (https://www.capstonedepot.live/).

Functionality supported around posts inculdes:
    making a new post
    viewing a post's details
    updating a post
    deleting a post

Author: David Onchuru
"""

from flask import render_template, url_for, flash, redirect, request, abort ,Blueprint
from flask_login import current_user, login_required
from capstone_depot import db  # Project database
from capstone_depot.models import Post  # Database table
from capstone_depot.posts.forms import PostForm  # Web form to put in Post details

# save_poster() is a utility method to check poster format and save it to a cloud storage service (currently Cloudinary).
# It returns a url with the link to the resource and also performs error checking
from capstone_depot.posts.utils import save_poster

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
     """
     Route to make a new post.

     This route initializes a form to take in the project's details
     The form details are then entered into the Post table in the database.
     """
     form = PostForm()
     # validate_on_submit() will validate the format of the form and make sure the user fills in the right fields before saving their changes to the database
     if form.validate_on_submit():
          # Preprocessing to get poster url in database table
          poster_url = None  # Default to None if no poster is provided
          if form.poster.data:  # Check if a file was uploaded for the poster field
               poster_url = save_poster(form.poster.data)  # Assign the saved file path to poster_file
               print(poster_url)

          post = Post(
               title=form.title.data,
               year = form.year.data,
               team_members = form.team_members.data,
               content=form.content.data,
               category=form.category.data,
               link=form.link.data,
               poster=poster_url,  # Assign the value of poster_file to the poster column
               author=current_user
          )

          print("***** BEFORE WE COMMIT TO DB ********") # useful for debugging
          db.session.add(post)
          db.session.commit()
          flash(f'Your project has been created!', 'success')
          return redirect(url_for('main.home'))

     return render_template('create_post.html', title='Upload a Project', form=form, legend='Upload a Project')


@posts.route("/post/<int:post_id>")
def post(post_id):
     """
     Route to view a project's details.

     All the project details are queried from the database using the post's id and rendered from the post HTML template.
     """
     post = Post.query.get_or_404(post_id)
     return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
     """
     Route to update a project's details.

     All the project details are queried from the database and prepopulated.
     After changes have been made, the post is updated and rendered dynamically with the Post HTML template.
     """
     post = Post.query.get_or_404(post_id)
     if post.author != current_user:
          abort(403)

     form = PostForm()

     if form.validate_on_submit():
          # Update the contents of the post in our db
          post.title = form.title.data
          post.year = form.year.data
          post.team_members = form.team_members.data
          post.content = form.content.data
          post.category = form.category.data

          # Patch for link bug. Check issue #37
          if form.link.data:
               post.link = form.link.data
          else:
               post.link = ""

          if form.poster.data:
               poster_url = save_poster(form.poster.data)
               post.poster = poster_url
          db.session.commit()
          flash('Your project has been updated!', 'success')
          return redirect(url_for('posts.post', post_id=post.id)) # Show user the updated post

     # After user has pressed the update post button
     # All form fields get pre-populated by querying the post's details from the database
     elif request.method == 'GET':
          form.title.data = post.title
          form.year.data = post.year
          form.team_members.data = post.team_members
          form.content.data = post.content
          form.category.data = post.category
          form.link.data = post.link
          form.poster.data = post.poster
     return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
     """
     Route to delete a post.

     Deletes the posts entry from the Posts table in the database.
     After delete action, user is redirected to home page.
     """
     post = Post.query.get_or_404(post_id)
     if post.author != current_user:
          abort(403)
     db.session.delete(post)
     db.session.commit()
     flash('Your project has been deleted!', 'success')
     return redirect(url_for('main.home'))

capstone_depot/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from capstone_depot import db, bcrypt
from capstone_depot.models import User, Post
from capstone_depot.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from capstone_depot.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    # if user is already logged in
    if current_user.is_authenticated:
         return redirect(url_for('main.home'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    print(form.errors)
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
         return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
            user = User.query.filter_by(email=form.email.data).first()
            if user and bcrypt.check_password_hash(user.password, form.password.data):
                 login_user(user, remember=form.remember.data)
                 # go to the page the user originally wanted to access but wasn't logged in
                 next_page = request.args.get('next')
                 return redirect(next_page) if next_page else redirect(url_for('main.home'))
            else:
                flash('Login Unsuccessful. Please check email and password', 'danger')

    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
     logout_user()
     return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_url = save_picture(form.picture.data)
            current_user.image_file = picture_url
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = current_user.image_file
    return render_template('account.html', title='Account', image_file=image_file, form=form)


''' Display the posts a specific user has '''
@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
     if current_user.is_authenticated:
         return redirect(url_for('main.home'))
     form = RequestResetForm()
     if form.validate_on_submit():
          user = User.query.filter_by(email=form.email.data).first()
          send_reset_email(user)
          flash('An email has been sent with instructions to reset your password', 'info')
          return redirect(url_for('users.login'))
     return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
     if current_user.is_authenticated:
         return redirect(url_for('main.home'))
     user = User.verify_reset_token(token)
     if user is None:
          flash('That is an invalid or expired token', 'warning')
          return redirect(url_for('users.reset_request'))
     form = ResetPasswordForm()
     if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
     return render_template('reset_token.html', title='Reset Password', form=form)

capstone_depot/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="container row">
        <div class="col-md-9 mt-3">

        {% if category %}
            <h1> Projects from the Department of {{ category }} </h1>
        {% endif %}

        {% for post in posts.items %}
            <div class="border mb-3 rounded-3">
                <div class="d-flex m-3">

                    <div class="flex-grow-1">

                        <div class="article-metadata">

                            <a class="mr-2 username" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>

                            <small class="text-muted float-end"> <i class="far fa-snowflake" aria-hidden="true"></i> {{ post.year }}</small>

                        </div>

                        <div>
                            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                        </div>

                        <p class="article-content"><strong>Team Members:</strong> {{ post.team_members }}</p>

                        <div class="mt-3 mb-3">
                            <!-- clickable poster image -->
                            {% if post.poster %}
                                <a href="{{ post.poster }}" target="_blank">
                                    <img class="img-fluid" style="max-width:90%" src="{{ post.poster }}">
                                </a>
                            {% endif %}
                        </div>

                        <p class="article-content">{{ post.content }}</p>


                        <div class="d-flex flex-wrap justify-content-between align-items-center mt-3 mb-3">
                            <h6 class="mr-3">Discipline:<a href="{{ url_for('categories.category_posts', category=post.category) }} "><span class="badge m-2">{{ post.category }}</span> </a></h6>

                            {% if post.link %}
                            <a class="social-icon-link" target="_blank" href="{{ post.link }}" style="text-decoration: none; opacity: 0.8;" onmouseover="this.style.opacity=1" onmouseout="this.style.opacity=0.8">
                                {% if post.link.startswith('https://github.com') %}
                                    <i class="fab fa-github fa-3x" aria-hidden="true" style="color: white;"></i>
                                {% elif post.link.startswith('https://www.youtube.com') or post.link.startswith('https://youtube.com') or post.link.startswith('https://youtu.be') %}
                                    <i class="fab fa-youtube fa-3x" aria-hidden="true" style="color: white;"></i>
                                {% else %}
                                     <i class="fas fa-link fa-3x" aria-hidden="true" style="color: white;"></i> <!-- Optional: Fallback icon -->
                                {% endif %}
                            </a>
                            {% endif %}
                        </div>

                    </div>
                </div>
            </div>
        {% endfor %}
        </div>

        <div class="col-md-3 mt-4">
            <div class="">
                <h3><i class="fa fa-compass" aria-hidden="true"></i> Explore</h3>
                <p class='text-muted'>Explore projects from other disciplines!</p>
                <ul class="list-group list-group-flush">
                    {% for category in categories %}
                        <li class="list-group-item"> <a class="categories" href="{{ url_for('categories.category_posts', category=category) }} "><i class="fa fa-graduation-cap" aria-hidden="true"></i>
                            {{ category }} </a> </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

    </div>

    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                {% if category %}
                    <a class="btn btn-secondary mb-4" href="{{ url_for('categories.category_posts', category=category, page=page_num) }}"> {{ page_num }}</a>
                {% else %}
                    <a class="btn btn-secondary mb-4" href="{{ url_for('main.home', page=page_num) }}"> {{ page_num }}</a>
                {% endif %}
            {% else %}
                {% if category %}
                    <a class="btn btn-outline-secondary mb-4" href="{{ url_for('categories.category_posts', category=category, page=page_num) }}"> {{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-secondary mb-4" href="{{ url_for('main.home', page=page_num) }}"> {{ page_num }}</a>
                {% endif %}
            {% endif %}
        {% else %}
            ...
        {% endif %}

    {% endfor %}

{% endblock content %}

capstone_depot/templates/layout.html
<!--this is what is shared between the different pages(html files)-->

<!DOCTYPE html>
<html>
  <head>
    <!--Adding Bootstrap-->

    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='main.css') }}"
    />

    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <!-- adding favicon -->
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="/static/favicon/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="/static/favicon/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="/static/favicon/png"
    />
    <link rel="manifest" href="/static/favicon/site.webmanifest" />

    <!-- adding Google Analytics -->
    <!-- Google tag (gtag.js) -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-RT1S6D1EDD"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag("js", new Date());

      gtag("config", "G-RT1S6D1EDD");
    </script>

    {% if title %}
    <title>Capstone Depot - {{ title }}</title>
    {% else %}
    <title>
      Capstone Depot | A shared repository for capstone projects. Please
      contribute yours!
    </title>
    {% endif %}

    <style>
      .github-icon {
        vertical-align: middle;
        width: 20px; /* Increased from 16px */
        height: 20px; /* Increased from 16px */
        transition: color 0.2s ease-in-out;
      }

      /* Remove individual hover effect from icon since it will inherit from parent */
      .github-icon:hover {
        color: inherit;
      }

      /* Add small spacing between icon and text */
      .github-icon {
        margin-right: 4px;
      }
    </style>
  </head>

  <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand me-3" href="/"
            ><i class="fas fa-archive" aria-hidden="true"></i> Capstone Depot</a
          >

          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarToggle"
            aria-controls="navbarToggle"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}"
                ><i class="fas fa-home" aria-hidden="true"></i> Home</a
              >
              <!-- <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a> -->
            </div>

            <!-- Navbar Right Side -->
            <div class="navbar-nav ms-auto">
              {% if current_user.is_authenticated %}

              <a
                class="nav-item nav-link me-3"
                href="{{ url_for('posts.new_post') }}"
                ><i class="fas fa-plus" aria-hidden="true"> </i> Upload Project
              </a>

              <a
                class="nav-item nav-link me-3"
                href="{{ url_for('users.account') }}"
              >
                <i class="fas fa-user" aria-hidden="true"></i> My Account
              </a>

              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">
                <i class="fas fa-sign-out-alt" aria-hidden="true"></i>
                Sign Out
              </a>

              {% else %}
              <a
                class="nav-item nav-link me-3"
                href="{{ url_for('main.about') }}"
              >
                <i class="fas fa-file-alt" aria-hidden="true"></i> About</a
              >

              <a
                class="nav-item nav-link me-3"
                href="{{ url_for('users.login') }}"
                ><i class="fas fa-sign-in-alt" aria-hidden="true"></i> Login</a
              >

              <a
                class="nav-item nav-link me-3"
                href="{{ url_for('users.register') }}"
              >
                <i class="fas fa-user-plus" aria-hidden="true"></i> Sign Up</a
              >

              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div>
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %} {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
          {% endfor %} {% endif %} {% endwith %} {% block content %}{% endblock
          %}
        </div>
      </div>
    </main>

    <!-- Remove the container if you want to extend the Footer to full width. -->

    <footer class="text-center text-white border-top container mt-5">
      <p class="d-flex justify-content-center align-items-center">
        <span class="me-1 mt-3">
          <a
            class="categories"
            target="_blank"
            rel="noopener noreferrer"
            href="https://github.com/donchuru/capstone_depot/issues/new"
            ><i class="fas fa-bug" aria-hidden="true"></i> Spotted a bug? Report
            an issue</a
          >
        </span>
        <span class="mx-2 mt-3">•</span>
        <span class="ms-1 mt-3">
          <a
            class="categories"
            target="_blank"
            rel="noopener noreferrer"
            href="https://github.com/donchuru/capstone_depot"
            title="View source code on GitHub"
          >
            <svg
              height="20"
              width="20"
              aria-hidden="true"
              viewBox="0 0 16 16"
              version="1.1"
              class="github-icon"
            >
              <path
                fill="currentColor"
                d="M8 0c4.42 0 8 3.58 8 8a8.013 8.013 0 0 1-5.45 7.59c-.4.08-.55-.17-.55-.38 0-.27.01-1.13.01-2.2 0-.75-.25-1.23-.54-1.48 1.78-.2 3.65-.88 3.65-3.95 0-.88-.31-1.59-.82-2.15.08-.2.36-1.02-.08-2.12 0 0-.67-.22-2.2.82-.64-.18-1.32-.27-2-.27-.68 0-1.36.09-2 .27-1.53-1.03-2.2-.82-2.2-.82-.44 1.1-.16 1.92-.08 2.12-.51.56-.82 1.28-.82 2.15 0 3.06 1.86 3.75 3.64 3.95-.23.2-.44.55-.51 1.07-.46.21-1.61.55-2.33-.66-.15-.24-.6-.83-1.23-.82-.67.01-.27.38.01.53.34.19.73.9.82 1.13.16.45.68 1.31 2.69.94 0 .67.01 1.3.01 1.49 0 .21-.15.45-.55.38A7.995 7.995 0 0 1 0 8c0-4.42 3.58-8 8-8Z"
              ></path>
            </svg>
            <span>Link to repo</span>
          </a>
        </span>
      </p>

      <div class="mt-2 mb-4">
        <a href="{{ url_for('main.about') }}" class="categories">
          About Page
        </a>
        <span class="mx-2">•</span>
        <a
          href="https://buy.stripe.com/3cs6s9cwl7RQ7qE144"
          class="categories"
          target="_blank"
          rel="noopener noreferrer"
        >
          <i class="fas fa-coffee"></i> Buy me a coffee
        </a>
      </div>

      <!-- Copyright -->
      <div class="text-center mb-4">© 2025 Copyright</div>
      <!-- Copyright -->
    </footer>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

capstone_depot/templates/post.html
{% extends "layout.html" %}
{% block content %}

    <div class="d-flex m-3">
        <div class="flex-grow-1">
            <div class="article-metadata">
                <a class="mr-2 username" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>

                <small class="text-muted"> <i class="far fa-snowflake" aria-hidden="true"></i> {{ post.year }}</small>

                {% if post.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href=" {{ url_for('posts.update_post', post_id=post.id) }}"> Update </a>
                    </div>
                {% endif %}

            </div>

            <h2 class="article-title">{{ post.title }}</a></h2>

            <p class="article-content"><strong>Team Members:</strong> {{ post.team_members }}</p>

            <div class="mt-3">
                <!-- clickable poster image -->
                {% if post.poster %}
                    <a href="{{ post.poster }}" target="_blank">
                        <img class="img-fluid" style="max-width:100%" src="{{ post.poster }}">
                    </a>
                {% endif %}
            </div>

            <div class="mt-2">
                <p class="article-content">{{ post.content }}</p>
            </div>

            <div class="d-flex flex-wrap justify-content-between align-items-center mt-3 mb-3">
                <h6 class="mr-3">Tag:<a href="{{ url_for('categories.category_posts', category=post.category) }} "><span class="badge m-2">{{ post.category }}</span> </a></h6>

                {% if post.link %}
                <a class="social-icon-link" target="_blank" href="{{ post.link }}" style="text-decoration: none; opacity: 0.8;" onmouseover="this.style.opacity=1" onmouseout="this.style.opacity=0.8">
                    {% if post.link.startswith('https://github.com') %}
                        <i class="fab fa-github fa-3x" aria-hidden="true" style="color: white;"></i>
                    {% elif post.link.startswith('https://www.youtube.com') or post.link.startswith('https://youtube.com') or post.link.startswith('https://youtu.be') %}
                        <i class="fab fa-youtube fa-3x" aria-hidden="true" style="color: white;"></i>
                    {% else %}
                         <i class="fas fa-link fa-3x" aria-hidden="true" style="color: white;"></i> <!-- Optional: Fallback icon -->
                    {% endif %}
                </a>
                {% endif %}
            </div>

            <!-- <div class="mt-5">
                <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal"> Delete </button>
            </div> -->
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-dark">
                    <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete this project?</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="border-dark modal-footer bg-dark">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

capstone_depot/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Reset Password </legend>

                <div class="form-group mb-3">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>

                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>

            <div class="form-group mb-3">
                {{ form.submit(class="btn btn-outline-primary") }}
            </div>

        </form>
    </div>

{% endblock content %}